version: '3'
services:
    apache:
        build: .docker/apache
        container_name: apache_gsheets_data
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/sf5
        depends_on:
          - php

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: mysql_gsheets_data
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf5
            MYSQL_USER: sf5
            MYSQL_PASSWORD: sf5
        ports:
          - "4306:3306"

    php:
        build: .docker/php
        container_name: php_gsheets_data
        volumes:
          - .:/home/wwwroot/sf5
        environment:
          - maildev_host=sf5_maildev_translation_service
        depends_on:
          - mysql